// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stronghold.AppDashboard.Data;

#nullable disable

namespace Stronghold.AppDashboard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216153312_AddAppOrdersIsAdmin")]
    partial class AddAppOrdersIsAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.AppDirectory", b =>
                {
                    b.Property<int>("AppDirectoryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppDirectoryEntryId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Icon")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemOwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("TechSupportId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppDirectoryEntryId");

                    b.HasIndex("SystemOwnerId");

                    b.HasIndex("TechSupportId");

                    b.ToTable("AppDirectory");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.AppDirectoryOrder", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("AppDirectoryEntryId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("UserId", "IsAdmin", "AppDirectoryEntryId");

                    b.HasIndex("AppDirectoryEntryId");

                    b.ToTable("AppDirectoryOrders");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.IntegratedApp", b =>
                {
                    b.Property<int>("IntegratedAppEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntegratedAppEntryId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Icon")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemOwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("TechSupportId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAuthorizationApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegratedAppEntryId");

                    b.HasIndex("SystemOwnerId");

                    b.HasIndex("TechSupportId");

                    b.ToTable("IntegratedApps");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.IntegratedAppOrder", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("IntegratedAppEntryId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("UserId", "IsAdmin", "IntegratedAppEntryId");

                    b.HasIndex("IntegratedAppEntryId");

                    b.ToTable("IntegratedAppOrders");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<Guid>("ADAdminsGroupGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADAdminsGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ADUsersGroupGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADUsersGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SettingsId");

                    b.HasIndex("ADAdminsGroupGUID")
                        .IsUnique();

                    b.HasIndex("ADUsersGroupGUID")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.SystemOwner", b =>
                {
                    b.Property<int>("SystemOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemOwnerId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemOwnerId");

                    b.ToTable("SystemOwners");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.TechSupport", b =>
                {
                    b.Property<int>("TechSupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechSupportId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechSupportId");

                    b.ToTable("TechSupports");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AzureAdObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.HasIndex("DisabledById");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.AppDirectory", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.SystemOwner", null)
                        .WithMany()
                        .HasForeignKey("SystemOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stronghold.AppDashboard.Data.Models.TechSupport", null)
                        .WithMany()
                        .HasForeignKey("TechSupportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.AppDirectoryOrder", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.IntegratedApp", null)
                        .WithMany()
                        .HasForeignKey("AppDirectoryEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stronghold.AppDashboard.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.IntegratedApp", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.SystemOwner", null)
                        .WithMany()
                        .HasForeignKey("SystemOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stronghold.AppDashboard.Data.Models.TechSupport", null)
                        .WithMany()
                        .HasForeignKey("TechSupportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.IntegratedAppOrder", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.IntegratedApp", null)
                        .WithMany()
                        .HasForeignKey("IntegratedAppEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stronghold.AppDashboard.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.User", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("DisabledById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.UserRole", b =>
                {
                    b.HasOne("Stronghold.AppDashboard.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stronghold.AppDashboard.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stronghold.AppDashboard.Data.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
