using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stronghold.AppDashboard.Data.Migrations
{
    /// <inheritdoc />
    public partial class Phase2A_AutoCa : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AutoCreateCa on AuditQuestion
            migrationBuilder.AddColumn<bool>(
                name: "AutoCreateCa",
                schema: "audit",
                table: "AuditQuestion",
                type: "bit",
                nullable: false,
                defaultValue: false);

            // Source on CorrectiveAction — distinguishes auto vs manual
            migrationBuilder.AddColumn<string>(
                name: "Source",
                schema: "audit",
                table: "CorrectiveAction",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "Manual");

            // QuestionId on CorrectiveAction — idempotency key for auto-CAs
            migrationBuilder.AddColumn<int>(
                name: "QuestionId",
                schema: "audit",
                table: "CorrectiveAction",
                type: "int",
                nullable: true);

            // Make FindingId nullable (auto-CAs may not have a finding at creation time)
            migrationBuilder.AlterColumn<int>(
                name: "FindingId",
                schema: "audit",
                table: "CorrectiveAction",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            // Filtered unique index: at most one auto-generated CA per (AuditId, QuestionId)
            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IX_CorrectiveAction_AutoGenerated
                ON [audit].[CorrectiveAction] ([AuditId], [QuestionId])
                WHERE [Source] = 'AutoGenerated' AND [QuestionId] IS NOT NULL AND [AuditId] IS NOT NULL;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX IF EXISTS IX_CorrectiveAction_AutoGenerated ON [audit].[CorrectiveAction];");

            migrationBuilder.AlterColumn<int>(
                name: "FindingId",
                schema: "audit",
                table: "CorrectiveAction",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.DropColumn(
                name: "QuestionId",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropColumn(
                name: "Source",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropColumn(
                name: "AutoCreateCa",
                schema: "audit",
                table: "AuditQuestion");
        }
    }
}
