using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stronghold.AppDashboard.Data.Migrations
{
    /// <inheritdoc />
    public partial class add_ca_quality_constraints : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "CK_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.AlterColumn<string>(
                name: "RootCause",
                schema: "audit",
                table: "CorrectiveAction",
                type: "nvarchar(2000)",
                maxLength: 2000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Priority",
                schema: "audit",
                table: "CorrectiveAction",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "Normal",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.CreateIndex(
                name: "IX_CorrectiveAction_AssignedToUserId",
                schema: "audit",
                table: "CorrectiveAction",
                column: "AssignedToUserId");

            migrationBuilder.CreateIndex(
                name: "IX_CorrectiveAction_AuditResponseId",
                schema: "audit",
                table: "CorrectiveAction",
                column: "AuditResponseId");

            migrationBuilder.CreateIndex(
                name: "IX_CorrectiveAction_DueDate",
                schema: "audit",
                table: "CorrectiveAction",
                column: "DueDate");

            migrationBuilder.CreateIndex(
                name: "IX_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction",
                column: "Status");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CorrectiveAction_Priority",
                schema: "audit",
                table: "CorrectiveAction",
                sql: "[Priority] IN ('Normal', 'Urgent')");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CorrectiveAction_Source",
                schema: "audit",
                table: "CorrectiveAction",
                sql: "[Source]   IN ('Manual', 'AutoGenerated')");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction",
                sql: "[Status]   IN ('Open', 'InProgress', 'Closed', 'Voided', 'Overdue')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_CorrectiveAction_AssignedToUserId",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropIndex(
                name: "IX_CorrectiveAction_AuditResponseId",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropIndex(
                name: "IX_CorrectiveAction_DueDate",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropIndex(
                name: "IX_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CorrectiveAction_Priority",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CorrectiveAction_Source",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction");

            migrationBuilder.AlterColumn<string>(
                name: "RootCause",
                schema: "audit",
                table: "CorrectiveAction",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(2000)",
                oldMaxLength: 2000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Priority",
                schema: "audit",
                table: "CorrectiveAction",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(20)",
                oldMaxLength: 20,
                oldDefaultValue: "Normal");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CorrectiveAction_Status",
                schema: "audit",
                table: "CorrectiveAction",
                sql: "[Status] IN ('Open', 'InProgress', 'Closed', 'Voided', 'Overdue')");
        }
    }
}
