using MediatR;
using Microsoft.EntityFrameworkCore;
using Stronghold.AppDashboard.Api.Authorization;
using Stronghold.AppDashboard.Data;
using Stronghold.AppDashboard.Shared.Enumerations;

namespace Stronghold.AppDashboard.Api.Domain.Audit.Audits;

[AllowedAuthorizationRole(
    AuthorizationRole.AuditManager, AuthorizationRole.AuditReviewer,
    AuthorizationRole.CorrectiveActionOwner, AuthorizationRole.ReadOnlyViewer,
    AuthorizationRole.ExecutiveViewer, AuthorizationRole.TemplateAdmin,
    AuthorizationRole.Administrator,
    AuthorizationRole.Auditor, AuthorizationRole.AuditAdmin, AuthorizationRole.Executive, AuthorizationRole.NormalUser)]
public class GetCorrectiveActions : IRequest<PagedCorrectiveActionsResult>
{
    public int?    DivisionId    { get; set; }
    public string? Status        { get; set; }
    public string? SearchText    { get; set; }
    public string? AssignedTo    { get; set; }
    public string? Source        { get; set; }   // "Manual" | "AutoGenerated" | null = all
    public string? Priority      { get; set; }   // "Normal" | "Urgent" | null = all
    public bool    OverdueOnly   { get; set; }
    public int     PageNumber    { get; set; } = 1;
    public int     PageSize      { get; set; } = 25;
}

public class PagedCorrectiveActionsResult
{
    public List<CorrectiveActionListItemDto> Items           { get; set; } = new();
    public int                               TotalCount      { get; set; }
    public int                               PageNumber      { get; set; }
    public int                               PageSize        { get; set; }
    public int                               TotalPages      => (int)Math.Ceiling((double)TotalCount / PageSize);
    // KPI counts across the full filtered set (not just this page)
    public int                               OpenCount       { get; set; }
    public int                               InProgressCount { get; set; }
    public int                               OverdueCount    { get; set; }
    public int                               ClosedCount     { get; set; }
}

public class CorrectiveActionListItemDto
{
    public int     Id              { get; set; }
    public int     AuditId         { get; set; }
    public string  DivisionCode    { get; set; } = null!;
    public string  DivisionName    { get; set; } = null!;
    public string? JobNumber       { get; set; }
    public string? AuditDate       { get; set; }
    public string  Description     { get; set; } = null!;
    public string? RootCause       { get; set; }
    public string  Status          { get; set; } = null!;
    public string  Source          { get; set; } = null!;
    public string? AssignedTo      { get; set; }
    public int?    AssignedToUserId { get; set; }
    public string  Priority        { get; set; } = "Normal";
    public string? DueDate         { get; set; }
    public string? CompletedDate   { get; set; }
    public bool    IsOverdue            { get; set; }
    public int     DaysOpen             { get; set; }
    public string  QuestionText         { get; set; } = null!;
    public string  SectionName          { get; set; } = null!;
    public DateTime CreatedAt           { get; set; }
    /// <summary>True when the CA's division requires a closure photo before closing.</summary>
    public bool    RequireClosurePhoto  { get; set; }
    /// <summary>Number of closure photos currently attached to this CA.</summary>
    public int     ClosurePhotoCount    { get; set; }
    /// <summary>Tracking number of the associated audit, e.g. "H26-012-IPT".</summary>
    public string? AuditTrackingNumber  { get; set; }
}

public class GetCorrectiveActionsHandler : IRequestHandler<GetCorrectiveActions, PagedCorrectiveActionsResult>
{
    private readonly AppDbContext _context;
    private readonly IAuditUserContext _userContext;

    public GetCorrectiveActionsHandler(AppDbContext context, IAuditUserContext userContext)
    {
        _context = context;
        _userContext = userContext;
    }

    public async Task<PagedCorrectiveActionsResult> Handle(
        GetCorrectiveActions request, CancellationToken cancellationToken)
    {
        var today      = DateOnly.FromDateTime(DateTime.UtcNow);
        var now        = DateTime.UtcNow;
        var pageNumber = Math.Max(1, request.PageNumber);
        var pageSize   = Math.Clamp(request.PageSize, 1, 200);

        // ── Build query using direct Audit navigation (fixes auto-generated CA visibility) ──
        var query = _context.CorrectiveActions
            .Include(ca => ca.Audit)
                .ThenInclude(a => a!.Division)
            .Include(ca => ca.Audit)
                .ThenInclude(a => a!.Header)
            .Include(ca => ca.Finding)
            .Include(ca => ca.Question)
            .AsNoTracking()
            .AsQueryable();

        // ── Division scope ───────────────────────────────────────────────────────
        if (!_userContext.IsGlobal && _userContext.AllowedDivisionIds is { Count: > 0 } allowed)
            query = query.Where(ca => ca.Audit != null && allowed.Contains(ca.Audit.DivisionId));

        // ── Filters ──────────────────────────────────────────────────────────────
        if (request.DivisionId.HasValue)
            query = query.Where(ca => ca.Audit != null && ca.Audit.DivisionId == request.DivisionId.Value);

        if (!string.IsNullOrEmpty(request.Status))
            query = query.Where(ca => ca.Status == request.Status);

        if (!string.IsNullOrEmpty(request.Source))
            query = query.Where(ca => ca.Source == request.Source);

        if (!string.IsNullOrEmpty(request.Priority))
            query = query.Where(ca => ca.Priority == request.Priority);

        if (!string.IsNullOrEmpty(request.AssignedTo))
        {
            var assignedToLower = request.AssignedTo.ToLower();
            query = query.Where(ca => ca.AssignedTo != null && ca.AssignedTo.ToLower().Contains(assignedToLower));
        }

        if (request.OverdueOnly)
            query = query.Where(ca => ca.Status != "Closed" && ca.Status != "Voided" && ca.DueDate.HasValue && ca.DueDate.Value < today);

        if (!string.IsNullOrEmpty(request.SearchText))
        {
            var q = request.SearchText.ToLower();
            query = query.Where(ca =>
                ca.Description.ToLower().Contains(q) ||
                (ca.AssignedTo != null && ca.AssignedTo.ToLower().Contains(q)) ||
                (ca.Finding != null && ca.Finding.QuestionTextSnapshot.ToLower().Contains(q)) ||
                (ca.Question != null && ca.Question.QuestionText.ToLower().Contains(q)));
        }

        // ── Compute KPI counts across the full filtered set (single grouped query) ──
        var kpiCounts = await query
            .GroupBy(_ => 1)
            .Select(g => new
            {
                Total      = g.Count(),
                Open       = g.Count(ca => ca.Status == "Open"),
                InProgress = g.Count(ca => ca.Status == "InProgress"),
                Overdue    = g.Count(ca => ca.Status != "Closed" && ca.Status != "Voided" && ca.DueDate.HasValue && ca.DueDate.Value < today),
                Closed     = g.Count(ca => ca.Status == "Closed"),
            })
            .FirstOrDefaultAsync(cancellationToken);

        var totalCount = kpiCounts?.Total ?? 0;

        // ── Apply ordering + paging ───────────────────────────────────────────
        var items = await query
            .OrderByDescending(ca => ca.CreatedAt)
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .Select(ca => new CorrectiveActionListItemDto
            {
                Id               = ca.Id,
                AuditId          = ca.AuditId ?? (ca.Finding != null ? ca.Finding.AuditId : 0),
                DivisionCode     = ca.Audit != null ? ca.Audit.Division.Code : "—",
                DivisionName     = ca.Audit != null ? ca.Audit.Division.Name : "—",
                JobNumber        = ca.Audit != null && ca.Audit.Header != null ? ca.Audit.Header.JobNumber : null,
                AuditDate        = ca.Audit != null && ca.Audit.Header != null && ca.Audit.Header.AuditDate.HasValue
                                       ? ca.Audit.Header.AuditDate.Value.ToString("yyyy-MM-dd")
                                       : null,
                Description      = ca.Description,
                RootCause        = ca.RootCause,
                Status           = ca.Status,
                Source           = ca.Source,
                AssignedTo       = ca.AssignedTo,
                AssignedToUserId = ca.AssignedToUserId,
                Priority         = ca.Priority,
                DueDate          = ca.DueDate.HasValue ? ca.DueDate.Value.ToString("yyyy-MM-dd") : null,
                CompletedDate    = ca.CompletedDate.HasValue ? ca.CompletedDate.Value.ToString("yyyy-MM-dd") : null,
                IsOverdue        = ca.Status != "Closed" && ca.Status != "Voided" && ca.DueDate.HasValue && ca.DueDate.Value < today,
                DaysOpen         = 0,
                QuestionText     = ca.Finding != null
                                       ? ca.Finding.QuestionTextSnapshot
                                       : (ca.Question != null ? ca.Question.QuestionText : ""),
                SectionName      = "",
                CreatedAt        = ca.CreatedAt,
                RequireClosurePhoto    = ca.Audit != null && ca.Audit.Division.RequireClosurePhoto,
                ClosurePhotoCount      = 0,
                AuditTrackingNumber    = ca.Audit != null ? ca.Audit.TrackingNumber : null,
            })
            .ToListAsync(cancellationToken);

        // ── Batch-load closure photo counts for this page only ────────────────
        var caIds       = items.Select(i => i.Id).ToList();
        var photoCounts = await _context.CorrectiveActionPhotos
            .Where(p => caIds.Contains(p.CorrectiveActionId))
            .GroupBy(p => p.CorrectiveActionId)
            .Select(g => new { g.Key, Count = g.Count() })
            .ToDictionaryAsync(x => x.Key, x => x.Count, cancellationToken);

        foreach (var item in items)
        {
            item.DaysOpen          = item.Status is "Closed" or "Voided"
                ? 0
                : Math.Max(0, (int)(now - item.CreatedAt).TotalDays);
            item.ClosurePhotoCount = photoCounts.TryGetValue(item.Id, out var cnt) ? cnt : 0;
        }

        return new PagedCorrectiveActionsResult
        {
            Items           = items,
            TotalCount      = totalCount,
            PageNumber      = pageNumber,
            PageSize        = pageSize,
            OpenCount       = kpiCounts?.Open       ?? 0,
            InProgressCount = kpiCounts?.InProgress ?? 0,
            OverdueCount    = kpiCounts?.Overdue    ?? 0,
            ClosedCount     = kpiCounts?.Closed     ?? 0,
        };
    }
}
