import { ref, computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import { useToast } from 'primevue/usetoast';
import type { CorrectiveActionListItemDto } from '@/apiclient/auditClient';
import { useAuditService } from '@/modules/audit-management/services/useAuditService';

function useCountUp(source: () => number, duration = 700) {
    const display = ref(0);
    watch(source, (rawTo: number) => {
        const to   = Number.isFinite(rawTo) ? rawTo : 0;
        const from = display.value;
        const start = performance.now();
        function tick(now: number) {
            const t    = Math.min((now - start) / duration, 1);
            const ease = 1 - Math.pow(1 - t, 3);
            display.value = Math.round(from + (to - from) * ease);
            if (t < 1) requestAnimationFrame(tick);
        }
        requestAnimationFrame(tick);
    }, { immediate: true });
    return display;
}

export const STATUS_OPTIONS = [
    { label: 'Open',        value: 'Open' },
    { label: 'In Progress', value: 'InProgress' },
    { label: 'Closed',      value: 'Closed' },
    { label: 'Voided',      value: 'Voided' },
];

export const SOURCE_OPTIONS = [
    { label: 'Manual',         value: 'Manual' },
    { label: 'Auto-Generated', value: 'AutoGenerated' },
];

export const PRIORITY_OPTIONS = [
    { label: 'Normal', value: 'Normal' },
    { label: 'Urgent', value: 'Urgent' },
];

export function useCorrectiveActions() {
    const service = useAuditService();
    const toast   = useToast();
    const router  = useRouter();

    // ── Filter state ──────────────────────────────────────────────────────────
    const loading           = ref(false);
    const exportingXlsx     = ref(false);
    const items             = ref<CorrectiveActionListItemDto[]>([]);
    const filterSearch      = ref('');
    const filterDivisionId  = ref<number | null>(null);
    const filterStatus      = ref<string | null>(null);
    const filterSource      = ref<string | null>(null);
    const filterPriority    = ref<string | null>(null);
    const filterOverdueOnly = ref(false);

    // ── Pagination ────────────────────────────────────────────────────────────
    const currentPage = ref(1);
    const pageSize    = ref(25);
    const totalCount  = ref(0);
    const totalPages  = computed(() => Math.ceil(totalCount.value / pageSize.value));

    // ── KPI counts (from server) ──────────────────────────────────────────────
    const kpiTotal      = computed(() => totalCount.value);
    const kpiOpen       = ref(0);
    const kpiInProgress = ref(0);
    const kpiOverdue    = ref(0);
    const kpiClosed     = ref(0);

    // ── Division options ──────────────────────────────────────────────────────
    const divisionOptions = ref<{ label: string; value: number }[]>([]);
    const divisionsLoaded = ref(false);

    // ── Animated KPI displays ─────────────────────────────────────────────────
    const displayTotal      = useCountUp(() => kpiTotal.value);
    const displayOpen       = useCountUp(() => kpiOpen.value);
    const displayInProgress = useCountUp(() => kpiInProgress.value);
    const displayOverdue    = useCountUp(() => kpiOverdue.value);
    const displayClosed     = useCountUp(() => kpiClosed.value);

    // ── Load ──────────────────────────────────────────────────────────────────
    async function load(resetPage = false) {
        if (resetPage) currentPage.value = 1;
        loading.value = true;
        try {
            const [result, divisions] = await Promise.all([
                service.getCorrectiveActions({
                    divisionId:  filterDivisionId.value,
                    status:      filterStatus.value,
                    searchText:  filterSearch.value || null,
                    source:      filterSource.value,
                    priority:    filterPriority.value,
                    overdueOnly: filterOverdueOnly.value,
                    pageNumber:  currentPage.value,
                    pageSize:    pageSize.value,
                }),
                divisionsLoaded.value ? Promise.resolve(null) : service.getDivisions(),
            ]);
            items.value         = result.items ?? [];
            totalCount.value    = result.totalCount ?? 0;
            kpiOpen.value       = result.openCount ?? 0;
            kpiInProgress.value = result.inProgressCount ?? 0;
            kpiOverdue.value    = result.overdueCount ?? 0;
            kpiClosed.value     = result.closedCount ?? 0;
            if (divisions) {
                divisionOptions.value = divisions.map(d => ({ label: `${d.code} — ${d.name}`, value: d.id }));
                divisionsLoaded.value = true;
            }
        } catch {
            toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load corrective actions.', life: 4000 });
        } finally {
            loading.value = false;
        }
    }

    function onPageChange(event: { page: number; rows: number }) {
        currentPage.value = event.page + 1;
        pageSize.value    = event.rows;
        load();
    }

    function loadFiltered() { load(true); }

    // ── KPI filter shortcuts ──────────────────────────────────────────────────
    const activeKpiFilter = computed<string | null>(() => {
        if (filterOverdueOnly.value)             return 'Overdue';
        if (filterStatus.value === 'Open')       return 'Open';
        if (filterStatus.value === 'InProgress') return 'InProgress';
        if (filterStatus.value === 'Closed')     return 'Closed';
        return 'Total';
    });

    function onKpiClick(key: 'Open' | 'InProgress' | 'Overdue' | 'Closed') {
        if (key === 'Overdue') {
            filterOverdueOnly.value = !filterOverdueOnly.value;
            if (filterOverdueOnly.value) filterStatus.value = null;
        } else {
            filterStatus.value      = filterStatus.value === key ? null : key;
            filterOverdueOnly.value = false;
        }
        loadFiltered();
    }

    function onKpiTotalClick() {
        filterStatus.value      = null;
        filterOverdueOnly.value = false;
        loadFiltered();
    }

    // ── Table helpers ─────────────────────────────────────────────────────────
    function rowClass(data: CorrectiveActionListItemDto): string {
        if (data.isOverdue)           return 'row--ca-overdue';
        if (data.status === 'Closed') return 'row--ca-closed';
        if (data.status === 'Voided') return 'row--ca-voided';
        return '';
    }

    function statusSeverity(data: CorrectiveActionListItemDto): string {
        if (data.isOverdue)               return 'danger';
        if (data.status === 'Closed')     return 'success';
        if (data.status === 'InProgress') return 'warning';
        if (data.status === 'Voided')     return 'secondary';
        return 'info';
    }

    function statusLabel(status: string): string {
        return status === 'InProgress' ? 'In Progress' : status;
    }

    function goToAudit(auditId: number) {
        router.push({ name: 'audit-management-review', params: { id: String(auditId) } });
    }

    // ── Excel export ──────────────────────────────────────────────────────────
    async function exportExcel() {
        exportingXlsx.value = true;
        try {
            const params: Record<string, string> = {};
            if (filterDivisionId.value)  params.divisionId  = String(filterDivisionId.value);
            if (filterStatus.value)      params.status      = filterStatus.value;
            if (filterSource.value)      params.source      = filterSource.value;
            if (filterPriority.value)    params.priority    = filterPriority.value;
            if (filterOverdueOnly.value) params.overdueOnly = 'true';
            if (filterSearch.value)      params.searchText  = filterSearch.value;
            const blob    = await service.downloadBlob('/v1/corrective-actions/export', params);
            const blobUrl = URL.createObjectURL(new Blob([blob], {
                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            }));
            const link    = document.createElement('a');
            link.href     = blobUrl;
            link.download = `corrective-actions-${new Date().toISOString().split('T')[0]}.xlsx`;
            link.click();
            URL.revokeObjectURL(blobUrl);
        } finally {
            exportingXlsx.value = false;
        }
    }

    return {
        // state
        loading, exportingXlsx, items,
        filterSearch, filterDivisionId, filterStatus, filterSource, filterPriority, filterOverdueOnly,
        currentPage, pageSize, totalCount, totalPages,
        kpiTotal, kpiOpen, kpiInProgress, kpiOverdue, kpiClosed,
        divisionOptions,
        // displays
        displayTotal, displayOpen, displayInProgress, displayOverdue, displayClosed,
        // load
        load, onPageChange, loadFiltered,
        // kpi
        activeKpiFilter, onKpiClick, onKpiTotalClick,
        // helpers
        rowClass, statusSeverity, statusLabel, goToAudit,
        // export
        exportExcel,
    };
}
