namespace Stronghold.AppDashboard.Data.Models.Audit;

/// <summary>
/// A remediation action assigned to address an AuditFinding.
/// Status lifecycle: Open → InProgress → Closed (or Overdue if past DueDate)
/// </summary>
public class CorrectiveAction : AuditableEntity
{
    /// <summary>FK to AuditFinding. Nullable for auto-generated CAs (finding may not exist at CA creation time).</summary>
    public int? FindingId { get; set; }

    /// <summary>Direct link to the parent audit (denormalized for efficient querying)</summary>
    public int? AuditId { get; set; }

    /// <summary>
    /// FK to AuditQuestion. Set for auto-generated CAs as the idempotency key: only one
    /// auto-generated CA may exist per (AuditId, QuestionId) pair — enforced by a filtered unique index.
    /// </summary>
    public int? QuestionId { get; set; }

    /// <summary>Direct link to the response that triggered this action</summary>
    public int? AuditResponseId { get; set; }

    public string Description { get; set; } = null!;
    public DateOnly? DueDate { get; set; }
    public DateOnly? CompletedDate { get; set; }

    public string? AssignedTo { get; set; }

    /// <summary>FK to Users.UserId — set when a known app user is assigned</summary>
    public int? AssignedToUserId { get; set; }

    /// <summary>"Open" | "InProgress" | "Overdue" | "Closed" | "Voided"</summary>
    public string Status { get; set; } = "Open";

    /// <summary>"Manual" | "AutoGenerated" — distinguishes auto-CAs from manually created ones.</summary>
    public string Source { get; set; } = "Manual";

    /// <summary>When true, the action cannot be closed without an evidence note</summary>
    public bool EvidenceRequired { get; set; }

    public DateTime? EvidenceReceivedDate { get; set; }
    public DateTime? ClosedDate { get; set; }

    // Navigation
    public AuditFinding? Finding { get; set; }
    public AuditQuestion? Question { get; set; }
    /// <summary>Direct navigation to the parent audit — enables efficient querying without going through Finding.</summary>
    public Audit? Audit { get; set; }
}
