/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ui/ActionBar.vue')['default']
    AlertBanner: typeof import('./src/components/ui/AlertBanner.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseButtonActivate: typeof import('./src/components/buttons/BaseButtonActivate.vue')['default']
    BaseButtonCancel: typeof import('./src/components/buttons/BaseButtonCancel.vue')['default']
    BaseButtonCreate: typeof import('./src/components/buttons/BaseButtonCreate.vue')['default']
    BaseButtonDelete: typeof import('./src/components/buttons/BaseButtonDelete.vue')['default']
    BaseButtonDisable: typeof import('./src/components/buttons/BaseButtonDisable.vue')['default']
    BaseButtonIconActivate: typeof import('./src/components/buttons/BaseButtonIconActivate.vue')['default']
    BaseButtonIconDelete: typeof import('./src/components/buttons/BaseButtonIconDelete.vue')['default']
    BaseButtonIconDisable: typeof import('./src/components/buttons/BaseButtonIconDisable.vue')['default']
    BaseButtonIconEdit: typeof import('./src/components/buttons/BaseButtonIconEdit.vue')['default']
    BaseButtonIconView: typeof import('./src/components/buttons/BaseButtonIconView.vue')['default']
    BaseButtonSave: typeof import('./src/components/buttons/BaseButtonSave.vue')['default']
    BaseButtonUpdate: typeof import('./src/components/buttons/BaseButtonUpdate.vue')['default']
    BaseDataTable: typeof import('./src/components/tables/BaseDataTable.vue')['default']
    BaseDialog: typeof import('./src/components/dialogs/BaseDialog.vue')['default']
    BaseFormField: typeof import('./src/components/forms/BaseFormField.vue')['default']
    BaseLoader: typeof import('./src/components/layout/BaseLoader.vue')['default']
    BasePageHeader: typeof import('./src/components/layout/BasePageHeader.vue')['default']
    BasePageSubheader: typeof import('./src/components/layout/BasePageSubheader.vue')['default']
    BasePDFViewer: typeof import('./src/components/layout/BasePDFViewer.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DevRoleSwitcher: typeof import('./src/components/layout/DevRoleSwitcher.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    FilterBar: typeof import('./src/components/ui/FilterBar.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPanel: typeof import('./src/components/ui/SectionPanel.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheMenu: typeof import('./src/components/layout/TheMenu.vue')['default']
    TheSubmenu: typeof import('./src/components/layout/TheSubmenu.vue')['default']
    TheTopBar: typeof import('./src/components/layout/TheTopBar.vue')['default']
  }
}
