/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButtonActivate: typeof import('./src/components/buttons/BaseButtonActivate.vue')['default']
    BaseButtonCancel: typeof import('./src/components/buttons/BaseButtonCancel.vue')['default']
    BaseButtonCreate: typeof import('./src/components/buttons/BaseButtonCreate.vue')['default']
    BaseButtonDelete: typeof import('./src/components/buttons/BaseButtonDelete.vue')['default']
    BaseButtonDisable: typeof import('./src/components/buttons/BaseButtonDisable.vue')['default']
    BaseButtonIconActivate: typeof import('./src/components/buttons/BaseButtonIconActivate.vue')['default']
    BaseButtonIconDelete: typeof import('./src/components/buttons/BaseButtonIconDelete.vue')['default']
    BaseButtonIconDisable: typeof import('./src/components/buttons/BaseButtonIconDisable.vue')['default']
    BaseButtonIconEdit: typeof import('./src/components/buttons/BaseButtonIconEdit.vue')['default']
    BaseButtonIconView: typeof import('./src/components/buttons/BaseButtonIconView.vue')['default']
    BaseButtonSave: typeof import('./src/components/buttons/BaseButtonSave.vue')['default']
    BaseButtonUpdate: typeof import('./src/components/buttons/BaseButtonUpdate.vue')['default']
    BaseDataTable: typeof import('./src/components/tables/BaseDataTable.vue')['default']
    BaseDialog: typeof import('./src/components/dialogs/BaseDialog.vue')['default']
    BaseFormField: typeof import('./src/components/forms/BaseFormField.vue')['default']
    BaseLoader: typeof import('./src/components/layout/BaseLoader.vue')['default']
    BasePageHeader: typeof import('./src/components/layout/BasePageHeader.vue')['default']
    BasePageSubheader: typeof import('./src/components/layout/BasePageSubheader.vue')['default']
    BasePDFViewer: typeof import('./src/components/layout/BasePDFViewer.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheMenu: typeof import('./src/components/layout/TheMenu.vue')['default']
    TheSubmenu: typeof import('./src/components/layout/TheSubmenu.vue')['default']
    TheTopBar: typeof import('./src/components/layout/TheTopBar.vue')['default']
  }
}
