/**
 * Corrective Actions Management — Full Contract Suite
 *
 * Covers: 2B-1 CA Dashboard + 2B-3 CA Closure Photo Requirement
 *         + Phase 2C SLA Tiers (Priority filter, Urgent badge)
 *
 * Tests every button, dialog, filter, KPI card, bulk action, and
 * closure-photo gate in CorrectiveActionsView.vue.
 *
 * API calls are intercepted and handled in-memory so this runs
 * without a live backend.  Enable PW_CA_LIVE_GATE=true to run
 * against the real API for full DB-write verification.
 */

import { Page, Route } from '@playwright/test';
import { test, expect } from './fixtures';
import { expectNoRuntimeErrors, gotoAndStabilize } from './utils/ui';

// ── Helpers ──────────────────────────────────────────────────────────────────

function replyJson(route: Route, payload: unknown, status = 200) {
    return route.fulfill({
        status,
        headers: { 'access-control-allow-origin': '*', 'content-type': 'application/json' },
        body: JSON.stringify(payload),
    });
}

function replyEmpty(route: Route) {
    return route.fulfill({ status: 204, headers: { 'access-control-allow-origin': '*' } });
}

// ── Seed data ─────────────────────────────────────────────────────────────────

const MOCK_DIVISIONS = [
    { id: 1, code: 'TKIE', name: 'TK Industrial East', requireClosurePhoto: false },
    { id: 2, code: 'CSL',  name: 'Central Services',   requireClosurePhoto: true  },
];

const MOCK_CAS = [
    {
        id: 1, auditId: 10,
        divisionCode: 'TKIE', divisionName: 'TK Industrial East',
        jobNumber: 'J-100', auditDate: '2026-04-01',
        description: 'Fix missing fall protection.',
        status: 'Open', source: 'Manual',
        priority: 'Normal',
        assignedTo: 'Alice', assignedToUserId: 5,
        dueDate: '2026-04-30', completedDate: null,
        isOverdue: false, daysOpen: 10,
        questionText: 'Fall protection systems in place?',
        sectionName: 'PPE',
        createdAt: '2026-04-07T00:00:00Z',
        requireClosurePhoto: false, closurePhotoCount: 0,
    },
    {
        id: 2, auditId: 11,
        divisionCode: 'CSL', divisionName: 'Central Services',
        jobNumber: 'J-200', auditDate: '2026-04-02',
        description: 'Replace damaged hard hats in Site B.',
        status: 'Open', source: 'AutoGenerated',
        priority: 'Urgent',
        assignedTo: 'Bob', assignedToUserId: 6,
        dueDate: '2026-04-10', completedDate: null,
        isOverdue: true, daysOpen: 25,
        questionText: 'PPE condition acceptable?',
        sectionName: 'PPE',
        createdAt: '2026-04-01T00:00:00Z',
        requireClosurePhoto: true, closurePhotoCount: 0,
    },
    {
        id: 3, auditId: 12,
        divisionCode: 'TKIE', divisionName: 'TK Industrial East',
        jobNumber: 'J-101', auditDate: '2026-03-15',
        description: 'Completed — lock-out procedure updated.',
        status: 'Closed', source: 'Manual',
        priority: 'Normal',
        assignedTo: 'Carol', assignedToUserId: 7,
        dueDate: '2026-03-20', completedDate: '2026-03-18',
        isOverdue: false, daysOpen: 0,
        questionText: 'LOTO procedures current?',
        sectionName: 'Lock-Out / Tag-Out',
        createdAt: '2026-03-10T00:00:00Z',
        requireClosurePhoto: false, closurePhotoCount: 0,
    },
    {
        id: 4, auditId: 13,
        divisionCode: 'TKIE', divisionName: 'TK Industrial East',
        jobNumber: 'J-102', auditDate: '2026-04-05',
        description: 'Update chemical inventory log.',
        status: 'InProgress', source: 'Manual',
        priority: 'Normal',
        assignedTo: null, assignedToUserId: null,
        dueDate: '2026-05-01', completedDate: null,
        isOverdue: false, daysOpen: 7,
        questionText: 'SDS binder up to date?',
        sectionName: 'Environmental',
        createdAt: '2026-04-05T00:00:00Z',
        requireClosurePhoto: false, closurePhotoCount: 0,
    },
];

// ── Mock API installer ────────────────────────────────────────────────────────

type MockState = {
    cas: typeof MOCK_CAS;
    capturedBulkRequests: unknown[];
    capturedCloseRequests: Record<number, unknown>;
    capturedEditRequests:  Record<number, unknown>;
    capturedPhotoUploads:  number[];
    capturedPriorityFilter: string[];
};

async function installCaMocks(page: Page): Promise<MockState> {
    const state: MockState = {
        cas: MOCK_CAS.map(c => ({ ...c })),
        capturedBulkRequests:  [],
        capturedCloseRequests: {},
        capturedEditRequests:  {},
        capturedPhotoUploads:  [],
        capturedPriorityFilter: [],
    };

    // Divisions
    await page.route(/\/v1\/divisions(\?.*)?$/i, (route) =>
        replyJson(route, MOCK_DIVISIONS),
    );

    // CA list (returns paged result since 2B-1 pagination update)
    await page.route(/\/v1\/audits\/corrective-actions(\?.*)?$/i, (route) => {
        const method = route.request().method().toUpperCase();
        if (method === 'GET') {
            // Capture priority filter parameter when present
            const url = new URL(route.request().url());
            const priorityParam = url.searchParams.get('priority');
            if (priorityParam) {
                state.capturedPriorityFilter.push(priorityParam);
            }
            // Filter CAs by priority if requested
            const filteredCas = priorityParam
                ? state.cas.filter(c => c.priority === priorityParam)
                : state.cas;
            const pagedResult = {
                items:          filteredCas,
                totalCount:     filteredCas.length,
                pageNumber:     1,
                pageSize:       25,
                totalPages:     1,
                openCount:       filteredCas.filter(c => c.status === 'Open').length,
                inProgressCount: filteredCas.filter(c => c.status === 'InProgress').length,
                overdueCount:    filteredCas.filter(c => c.isOverdue).length,
                closedCount:     filteredCas.filter(c => c.status === 'Closed').length,
            };
            return replyJson(route, pagedResult);
        }
        // POST = assignCorrectiveAction (not used in this view)
        return replyJson(route, {});
    });

    // CA bulk update
    await page.route(/\/v1\/audits\/corrective-actions\/bulk(\?.*)?$/i, async (route) => {
        const body = JSON.parse(route.request().postData() ?? '{}');
        state.capturedBulkRequests.push(body);

        const successCount = (body.correctiveActionIds as number[]).length;
        body.correctiveActionIds.forEach((id: number) => {
            const ca = state.cas.find(c => c.id === id);
            if (ca) {
                if (body.action === 'status') ca.status = body.newStatus;
                if (body.action === 'reassign') ca.assignedTo = body.newAssignee ?? null;
            }
        });

        return replyJson(route, { successCount, failedIds: [], errors: [] });
    });

    // CA close  PUT /v1/audits/corrective-actions/{id}/close
    await page.route(/\/v1\/audits\/corrective-actions\/(\d+)\/close(\?.*)?$/i, async (route) => {
        const idMatch = route.request().url().match(/\/corrective-actions\/(\d+)\/close/i);
        const id = idMatch ? Number(idMatch[1]) : -1;
        const body = JSON.parse(route.request().postData() ?? route.request().postData() ?? '{}');
        state.capturedCloseRequests[id] = body;
        const ca = state.cas.find(c => c.id === id);
        if (ca) ca.status = 'Closed';
        return replyEmpty(route);
    });

    // CA edit  PUT /v1/audits/corrective-actions/{id}  (not /close, not /photos)
    await page.route(/\/v1\/audits\/corrective-actions\/(\d+)(\?.*)?$/i, async (route) => {
        const method = route.request().method().toUpperCase();
        const idMatch = route.request().url().match(/\/corrective-actions\/(\d+)/i);
        const id = idMatch ? Number(idMatch[1]) : -1;

        if (method === 'PUT') {
            const body = JSON.parse(route.request().postData() ?? '{}');
            state.capturedEditRequests[id] = body;
            const ca = state.cas.find(c => c.id === id);
            if (ca) {
                ca.description = body.description ?? ca.description;
                ca.assignedTo  = body.assignedTo  ?? ca.assignedTo;
            }
            return replyEmpty(route);
        }
        return replyJson(route, state.cas.find(c => c.id === id) ?? {});
    });

    // CA closure photo upload  POST /v1/audits/corrective-actions/{id}/photos
    await page.route(/\/v1\/audits\/corrective-actions\/(\d+)\/photos(\?.*)?$/i, async (route) => {
        const idMatch = route.request().url().match(/\/corrective-actions\/(\d+)\/photos/i);
        const id = idMatch ? Number(idMatch[1]) : -1;
        state.capturedPhotoUploads.push(id);
        const ca = state.cas.find(c => c.id === id);
        if (ca) ca.closurePhotoCount += 1;
        return replyJson(route, { id: 99, correctiveActionId: id, fileName: 'photo.jpg', filePath: '/photos/photo.jpg', fileSizeBytes: 102400, uploadedAt: new Date().toISOString(), uploadedBy: 'Test' });
    });

    // Excel export — return empty blob
    await page.route(/\/v1\/corrective-actions\/export(\?.*)?$/i, (route) =>
        route.fulfill({ status: 200, headers: { 'access-control-allow-origin': '*', 'content-type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }, body: Buffer.alloc(0) }),
    );


    // Users with audit roles — needed by AutoComplete in Reassign dialogs
    await page.route(/\/v1\/admin\/users\/audit-roles(\?.*)?$/i, (route) =>
        replyJson(route, [
            { userId: 10, email: 'dave.smith@example.com', firstName: 'Dave', lastName: 'Smith', roleName: 'Auditor' },
            { userId: 11, email: 'alice.jones@example.com', firstName: 'Alice', lastName: 'Jones', roleName: 'Reviewer' },
        ]),
    );

    return state;
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Corrective Actions Dashboard — page render & KPI cards', () => {
    test('page loads and KPI cards reflect seed data counts', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Page header or KPI cards visible
        const kpiCards = page.locator('.kpi-card');
        await expect(kpiCards.first()).toBeVisible({ timeout: 8000 });

        // 4 CAs total — counts:  Open=2, InProgress=1, Closed=1, Overdue=1
        const cardTexts = await kpiCards.allTextContents();
        const allNums   = cardTexts.join(' ');
        expect(allNums).toMatch(/4/);   // Total
        expect(allNums).toMatch(/2/);   // Open
        expect(allNums).toMatch(/1/);   // InProgress or Closed

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('DataTable renders all four CA rows', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await expect.poll(() => rows.count()).toBeGreaterThanOrEqual(4);

        // Spot-check description text appears
        await expect(page.locator('text=Fix missing fall protection.')).toBeVisible();

        // Auto-CA badge visible for id=2
        await expect(page.locator('.bg-purple-900\\/60')).toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });
});

test.describe('Corrective Actions Dashboard — filter bar', () => {
    test('search input is visible and triggers reload on Enter', async ({ page, runtimeErrors }) => {
        let caFetchCount = 0;
        await installCaMocks(page);
        await page.route(/\/v1\/audits\/corrective-actions(\?.*)?$/i, async (route) => {
            if (route.request().method().toUpperCase() === 'GET') caFetchCount++;
            return replyJson(route, MOCK_CAS);
        });

        await gotoAndStabilize(page, '/audit-management/corrective-actions');
        const initialFetches = caFetchCount;

        await page.locator('input[placeholder*="Description"]').fill('fall');
        await page.keyboard.press('Enter');
        await page.waitForTimeout(400);

        expect(caFetchCount).toBeGreaterThan(initialFetches);
        expectNoRuntimeErrors(runtimeErrors);
    });

    test('division dropdown is visible and populated', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Open division dropdown
        const dropdowns = page.locator('.p-dropdown');
        await expect(dropdowns.first()).toBeVisible({ timeout: 8000 });
        await dropdowns.first().click();
        await expect(page.locator('.p-dropdown-item', { hasText: 'TKIE' }).first()).toBeVisible();
        await page.keyboard.press('Escape');

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('overdue-only toggle button fires', async ({ page, runtimeErrors }) => {
        let overdueRequested = false;
        await installCaMocks(page);
        await page.route(/\/v1\/audits\/corrective-actions(\?.*)?$/i, async (route) => {
            const url = new URL(route.request().url());
            if (url.searchParams.get('overdueOnly') === 'true') overdueRequested = true;
            return replyJson(route, MOCK_CAS);
        });

        await gotoAndStabilize(page, '/audit-management/corrective-actions');
        await page.locator('button', { hasText: 'Overdue Only' }).first().click();
        await page.waitForTimeout(400);
        expect(overdueRequested).toBe(true);
        expectNoRuntimeErrors(runtimeErrors);
    });

    test('export button is visible and clickable without error', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');
        const exportBtn = page.locator('button', { hasText: 'Export' });
        await expect(exportBtn).toBeVisible({ timeout: 8000 });
        await exportBtn.click();
        await page.waitForTimeout(300);
        expectNoRuntimeErrors(runtimeErrors);
    });
});

test.describe('Corrective Actions Dashboard — row action buttons', () => {
    test('edit button is visible and opens Edit dialog for open CA', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Hover first row to reveal actions
        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        const editBtn = firstRow.locator('button[aria-label*="Edit"], button.p-button-icon-only').first();
        // Fallback: find button by icon class
        const pencilBtn = firstRow.locator('button:has(.pi-pencil)');
        await expect(pencilBtn).toBeVisible({ timeout: 5000 });
        await pencilBtn.click();

        await expect(page.getByRole('dialog', { name: 'Edit Corrective Action' })).toBeVisible();
        expectNoRuntimeErrors(runtimeErrors);
    });

    test('edit dialog is pre-populated with existing CA data', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-pencil)').click();

        const dialog = page.getByRole('dialog', { name: 'Edit Corrective Action' });
        await expect(dialog).toBeVisible();
        // Description textarea should not be empty
        const descTA = dialog.locator('textarea').first();
        const val = await descTA.inputValue();
        expect(val.trim().length).toBeGreaterThan(0);

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('edit dialog Save Changes disabled when description cleared', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-pencil)').click();

        const dialog = page.getByRole('dialog', { name: 'Edit Corrective Action' });
        const descTA = dialog.locator('textarea').first();
        await descTA.clear();

        const saveBtn = dialog.locator('button', { hasText: 'Save Changes' });
        await expect(saveBtn).toBeDisabled();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('edit dialog submits PUT request and closes', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-pencil)').click();

        const dialog = page.getByRole('dialog', { name: 'Edit Corrective Action' });
        const descTA = dialog.locator('textarea').first();
        await descTA.fill('Updated description — QA test');

        await dialog.locator('button', { hasText: 'Save Changes' }).click();
        await expect(dialog).toBeHidden({ timeout: 5000 });

        // Verify the API received the PUT
        expect(Object.keys(state.capturedEditRequests).length).toBeGreaterThan(0);

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('close button opens Close CA dialog for open CA', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Find an open CA row (not Closed/Voided) — first row is id=1
        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        const closeBtn = firstRow.locator('button:has(.pi-check)');
        await expect(closeBtn).toBeVisible({ timeout: 5000 });
        await closeBtn.click();

        await expect(page.getByRole('dialog', { name: 'Close Corrective Action' })).toBeVisible();
        expectNoRuntimeErrors(runtimeErrors);
    });

    test('close dialog: Close Action button disabled until notes entered', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-check)').click();

        const dialog = page.getByRole('dialog', { name: 'Close Corrective Action' });
        const closeActionBtn = dialog.locator('button', { hasText: 'Close Action' });

        // Without notes — disabled
        await expect(closeActionBtn).toBeDisabled();

        // After entering notes — enabled
        await dialog.getByPlaceholder('Describe what was done to resolve this action', { exact: false }).fill('All corrected on site.');
        await expect(closeActionBtn).toBeEnabled();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('close dialog without photo requirement submits successfully', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // id=1 has requireClosurePhoto=false
        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-check)').click();

        const dialog = page.getByRole('dialog', { name: 'Close Corrective Action' });
        await dialog.getByPlaceholder('Describe what was done to resolve this action', { exact: false }).fill('Fixed and verified.');
        await dialog.locator('button', { hasText: 'Close Action' }).click();

        await expect(dialog).toBeHidden({ timeout: 5000 });
        expect(state.capturedCloseRequests[1]).toBeDefined();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('close button absent on already-closed CA', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // id=3 is Closed — it should be the third row
        const rows = page.locator('.p-datatable-tbody > tr');
        await expect.poll(() => rows.count()).toBeGreaterThanOrEqual(3);

        let foundClosedRowWithNoCloseBtn = false;
        for (let i = 0; i < await rows.count(); i++) {
            const row = rows.nth(i);
            await row.hover();
            const checkBtns = row.locator('button:has(.pi-check)');
            const cnt = await checkBtns.count();
            // Closed rows should have cnt === 0
            if (cnt === 0) {
                foundClosedRowWithNoCloseBtn = true;
                break;
            }
        }
        expect(foundClosedRowWithNoCloseBtn).toBe(true);

        expectNoRuntimeErrors(runtimeErrors);
    });
});

test.describe('Corrective Actions Dashboard — closure photo requirement (2B-3)', () => {
    test('close dialog shows photo upload zone when requireClosurePhoto=true', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // id=2 has requireClosurePhoto=true — find that row (overdue, "Replace damaged hard hats")
        const targetRow = page.locator('.p-datatable-tbody > tr', { hasText: 'Replace damaged hard hats' });
        await targetRow.hover();
        const closeBtn = targetRow.locator('button:has(.pi-check)');
        await expect(closeBtn).toBeVisible({ timeout: 5000 });
        await closeBtn.click();

        const dialog = page.getByRole('dialog', { name: 'Close Corrective Action' });
        await expect(dialog).toBeVisible();

        // Upload zone should be present
        await expect(dialog.locator('text=Closure Photo')).toBeVisible();
        await expect(dialog.locator('.pi-camera')).toBeVisible();

        // Close Action button disabled even with notes — no photo yet
        await dialog.getByPlaceholder('Describe what was done to resolve this action', { exact: false }).fill('Replaced all hard hats.');
        const closeActionBtn = dialog.locator('button', { hasText: 'Close Action' });
        await expect(closeActionBtn).toBeDisabled();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('close dialog photo requirement: button enabled after file upload succeeds', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const targetRow = page.locator('.p-datatable-tbody > tr', { hasText: 'Replace damaged hard hats' });
        await targetRow.hover();
        await targetRow.locator('button:has(.pi-check)').click();

        const dialog = page.getByRole('dialog', { name: 'Close Corrective Action' });
        await dialog.getByPlaceholder('Describe what was done to resolve this action', { exact: false }).fill('All hard hats replaced and verified.');

        // Simulate file input selection
        const fileInput = dialog.locator('input[type="file"]');
        await fileInput.setInputFiles({
            name: 'closure.jpg',
            mimeType: 'image/jpeg',
            buffer: Buffer.from('fake-image-data'),
        });

        // Wait for upload spinner to resolve
        await expect(dialog.locator('.pi-check-circle')).toBeVisible({ timeout: 5000 });
        await expect(dialog.locator('text=Uploaded')).toBeVisible();

        // Now Close Action should be enabled
        await expect(dialog.locator('button', { hasText: 'Close Action' })).toBeEnabled({ timeout: 3000 });

        // Verify the photo upload API was called
        expect(state.capturedPhotoUploads).toContain(2);

        expectNoRuntimeErrors(runtimeErrors);
    });
});

test.describe('Corrective Actions Dashboard — bulk actions', () => {
    test('selecting a row shows bulk action toolbar', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });

        // Click first row checkbox
        const checkbox = rows.first().locator('.p-checkbox');
        await checkbox.click();

        await expect(page.locator('text=action selected').or(page.locator('text=actions selected'))).toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk toolbar: Mark In Progress button fires bulk API', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        const bulkBar = page.locator('.bg-blue-900\\/40');
        await expect(bulkBar).toBeVisible();
        await bulkBar.locator('button', { hasText: 'Mark In Progress' }).click();

        await page.waitForTimeout(500);
        const bulkReq = state.capturedBulkRequests.find((r: any) => r.action === 'status' && r.newStatus === 'InProgress');
        expect(bulkReq).toBeDefined();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk toolbar: Close All opens Bulk Close dialog', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        await page.locator('.bg-blue-900\\/40').locator('button', { hasText: 'Close All' }).click();
        await expect(page.getByRole('dialog', { name: /Close .* Corrective Actions/ })).toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk close dialog: Close All button disabled until notes entered', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();
        await page.locator('.bg-blue-900\\/40').locator('button', { hasText: 'Close All' }).click();

        const dialog = page.getByRole('dialog', { name: /Close .* Corrective Actions/ });
        await expect(dialog.locator('button', { hasText: 'Close All' })).toBeDisabled();
        await dialog.locator('textarea').fill('Batch close notes.');
        await expect(dialog.locator('button', { hasText: 'Close All' })).toBeEnabled();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk toolbar: Void All fires bulk API with Voided status', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        await page.locator('.bg-blue-900\\/40').locator('button', { hasText: 'Void All' }).click();
        await page.waitForTimeout(500);

        const bulkReq = state.capturedBulkRequests.find((r: any) => r.action === 'status' && r.newStatus === 'Voided');
        expect(bulkReq).toBeDefined();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk toolbar: Reassign button opens Bulk Reassign dialog', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        await page.locator('.bg-blue-900\\/40').locator('button', { hasText: 'Reassign' }).click();
        await expect(page.getByRole('dialog', { name: /Reassign .* Corrective Actions/ })).toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('bulk reassign dialog submits reassign request', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        await page.locator('.bg-blue-900\\/40').locator('button', { hasText: 'Reassign' }).click();
        const dialog = page.getByRole('dialog', { name: /Reassign .* Corrective Actions/ });

        // AutoComplete requires selecting from suggestions (force-selection=true).
        // Type to trigger @complete, wait for suggestion panel, click the suggestion.
        const autocompleteInput = dialog.locator('.p-autocomplete input');
        await autocompleteInput.fill('Dave');
        const suggestionItem = page.locator('.p-autocomplete-item', { hasText: 'Dave Smith' });
        await expect(suggestionItem).toBeVisible({ timeout: 5000 });
        await suggestionItem.click();

        await dialog.locator('button', { hasText: 'Reassign All' }).click();

        await page.waitForTimeout(500);
        const bulkReq = state.capturedBulkRequests.find((r: any) => r.action === 'reassign');
        expect(bulkReq).toBeDefined();
        expect((bulkReq as any).newAssignee).toBe('Dave Smith');

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('deselect button clears selection and hides bulk toolbar', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await rows.first().locator('.p-checkbox').click();

        const bulkBar = page.locator('.bg-blue-900\\/40');
        await expect(bulkBar).toBeVisible();
        await bulkBar.locator('button:has(.pi-times)').click();
        await expect(bulkBar).not.toBeVisible({ timeout: 3000 });

        expectNoRuntimeErrors(runtimeErrors);
    });
});

test.describe('Corrective Actions Dashboard — Cancel buttons close dialogs', () => {
    test('Edit dialog Cancel closes it', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-pencil)').click();

        const dialog = page.getByRole('dialog', { name: 'Edit Corrective Action' });
        await expect(dialog).toBeVisible();
        await dialog.locator('button', { hasText: 'Cancel' }).click();
        await expect(dialog).toBeHidden({ timeout: 3000 });

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('Close CA dialog Cancel closes it', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        const firstRow = page.locator('.p-datatable-tbody > tr').first();
        await firstRow.hover();
        await firstRow.locator('button:has(.pi-check)').click();

        const dialog = page.getByRole('dialog', { name: 'Close Corrective Action' });
        await expect(dialog).toBeVisible();
        await dialog.locator('button', { hasText: 'Cancel' }).click();
        await expect(dialog).toBeHidden({ timeout: 3000 });

        expectNoRuntimeErrors(runtimeErrors);
    });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2C: SLA Tiers — Priority field and Priority filter tests
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Corrective Actions Dashboard — SLA tiers / Priority (Phase 2C)', () => {
    test('priority field appears on all CA items in mock API response', async ({ page, runtimeErrors }) => {
        // Verify mock data has the priority field — this validates the field contract
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // All 4 rows should render without error even when priority field present
        const rows = page.locator('.p-datatable-tbody > tr');
        await expect(rows.first()).toBeVisible({ timeout: 8000 });
        await expect.poll(() => rows.count()).toBeGreaterThanOrEqual(4);

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('CA with priority=Urgent shows red Urgent badge in description column', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // id=2 has priority='Urgent' — find its row
        const urgentRow = page.locator('.p-datatable-tbody > tr', { hasText: 'Replace damaged hard hats' });
        await expect(urgentRow).toBeVisible({ timeout: 8000 });

        // Verify the Urgent badge renders with the red styling
        const urgentBadge = urgentRow.locator('.bg-red-900\\/60');
        await expect(urgentBadge).toBeVisible();
        await expect(urgentBadge).toContainText('Urgent');

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('CA with priority=Normal does NOT show Urgent badge', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // id=1 has priority='Normal' — verify no Urgent badge in its row
        const normalRow = page.locator('.p-datatable-tbody > tr', { hasText: 'Fix missing fall protection.' });
        await expect(normalRow).toBeVisible({ timeout: 8000 });

        const urgentBadgeInRow = normalRow.locator('.bg-red-900\\/60');
        await expect(urgentBadgeInRow).not.toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('Priority filter dropdown is visible in the filter bar', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // The Priority label should exist above its dropdown
        await expect(page.locator('label', { hasText: 'Priority' })).toBeVisible({ timeout: 8000 });

        // There should be at least 4 dropdowns (Division, Status, Source, Priority)
        const dropdowns = page.locator('.p-dropdown');
        const count = await dropdowns.count();
        expect(count).toBeGreaterThanOrEqual(4);

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('Priority filter dropdown contains Normal and Urgent options', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Find the Priority dropdown — it's the last one (Division, Status, Source, Priority)
        const dropdowns = page.locator('.p-dropdown');
        const count = await dropdowns.count();
        // Click the Priority dropdown (last one before Overdue toggle)
        const priorityDropdown = dropdowns.nth(count - 1);
        await priorityDropdown.click();

        // Options must include Normal and Urgent
        await expect(page.locator('.p-dropdown-item', { hasText: 'Normal' })).toBeVisible();
        await expect(page.locator('.p-dropdown-item', { hasText: 'Urgent' })).toBeVisible();

        await page.keyboard.press('Escape');
        expectNoRuntimeErrors(runtimeErrors);
    });

    test('selecting Urgent in Priority filter sends priority=Urgent to the API', async ({ page, runtimeErrors }) => {
        const state = await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Open the Priority dropdown and select "Urgent"
        const dropdowns = page.locator('.p-dropdown');
        const count = await dropdowns.count();
        const priorityDropdown = dropdowns.nth(count - 1);
        await priorityDropdown.click();
        await page.locator('.p-dropdown-item', { hasText: 'Urgent' }).first().click();
        await page.waitForTimeout(500);

        // The filter should have triggered an API call with priority=Urgent
        expect(state.capturedPriorityFilter).toContain('Urgent');

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('filtering by Urgent priority shows only Urgent CAs in the table', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Select Urgent in Priority dropdown
        const dropdowns = page.locator('.p-dropdown');
        const count = await dropdowns.count();
        const priorityDropdown = dropdowns.nth(count - 1);
        await priorityDropdown.click();
        await page.locator('.p-dropdown-item', { hasText: 'Urgent' }).first().click();
        await page.waitForTimeout(600);

        // After Urgent filter: only id=2 matches → 1 row
        const rows = page.locator('.p-datatable-tbody > tr');
        await expect.poll(() => rows.count()).toBe(1);

        // That row should be the Urgent CA (id=2)
        await expect(page.locator('text=Replace damaged hard hats')).toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });

    test('filtering by Normal priority shows only Normal CAs in the table', async ({ page, runtimeErrors }) => {
        await installCaMocks(page);
        await gotoAndStabilize(page, '/audit-management/corrective-actions');

        // Select Normal in Priority dropdown
        const dropdowns = page.locator('.p-dropdown');
        const count = await dropdowns.count();
        const priorityDropdown = dropdowns.nth(count - 1);
        await priorityDropdown.click();
        await page.locator('.p-dropdown-item', { hasText: 'Normal' }).first().click();
        await page.waitForTimeout(600);

        // After Normal filter: ids 1, 3, 4 match → 3 rows
        const rows = page.locator('.p-datatable-tbody > tr');
        await expect.poll(() => rows.count()).toBe(3);

        // Urgent CA (id=2) should not appear
        await expect(page.locator('text=Replace damaged hard hats')).not.toBeVisible();

        expectNoRuntimeErrors(runtimeErrors);
    });
});
